biolab/orange3-geo

orangecontrib/geo/mapper.py

When running from development branch, Choropleth stalls forever, since I have not merged in the json branch.
If loading of polygons failed, raise the exception that occurred instead of waiting forever.
If this should be done differently, let me know and I will change it.

mapper: raise exception in wait_until_loaded

---

.travis.yml
orangecontrib/geo/widgets/tests/test_owmap.py

Fixes falling Travis
Update Python version (Orange requires Python 3.6 or newer),
fix PyQt version (new versions lack QtWebEngineWidgets),
fix falling OWMep test (until function timeouts).

[FIX] Fix/travis python

---

orangecontrib/geo/widgets/_leaflet/owmap.js

Fixes #48 
Points sometimes disappear.
I couldn't find the source of the call to JS function add_markers with an undefined list. It doesn't appear to be from within python. Still, this fix resolves the issue by ignoring such calls.

[FIX] OWMap: resolve points disappearing

---

orangecontrib/geo/widgets/owmap.py

Fixes #59
Use automatically detected latitude and longitude only if both where detected.

OWGeoMap: automatically set lat and lon only if bouth are known

---

orangecontrib/geo/widgets/owmap.py

Fixes Error (RuntimeError: wrapped C/C++ object of type OWMap has been deleted) when the widget is deleted during points drawing.
Stop drawing function.

[FIX] OWMap: stop running when deleted

---

orangecontrib/geo/widgets/owmap.py

Fixes #51 
Data points where redrawen on new data befor color/label/shape/size where updated.
Disable redrawing on setting map data.

OWMap: disable redrawing when setting map data

---

orangecontrib/geo/widgets/owmap.py
orangecontrib/geo/widgets/tests/test_owmap.py

Fixes #55 and (partially?) #69.
Regarding #55: prevents change of jittering and shadows its value when 'Cluster points' is checked.  
Regarding #69: plots missing values for **discrete** variables with a gray color (somewhat arbitrarily chosen, please feel free to suggest an alternative, if it does not fit the color scheme). The handling of missing values is local to this widget and does not change any of the attribute's properties.  
In a nutshell, nans get assigned a new (previously unassigned) integer, which maps to gray color.

Geo map fixes

---

orangecontrib/geo/widgets/owmap.py

Fixes #84.
Remove HTTP2AllowedAttribute.
This is a QTBUG-61397, which is fixed in version 5.12. The old installer still comes with qt=5.9.

GeoMap: failing to load tiles

---

.travis.yml

Tests fail due to scikit-learn change which was fixed in 3.25.1
Lifting version

Travis: raise minimum Orange version for testing to 3.25.1

---

doc/conf.py
doc/static/custom.css
orangecontrib/geo/widgets/__init__.py
setup.py

While ago we discussed that we will use the same documentation theme for add-ons. After some discussion, we decided on sphinx-rtd-theme. The alternative is Alabaster but its sidebar is not so readable and it breaks long addon names in two lines.
With this PR I am implementing the sphinx-rtd-theme. I also changed that the menu bar collapses on the medium screen already (before it collapsed on small screens). On the medium screen, the content column was narrow already and it works well for widget documentation in Orange since at the default Orange help window size the sidebar is collapsed.

Change documentation theme to sphinx_rtd_theme

---

orangecontrib/geo/widgets/owchoropleth.py
orangecontrib/geo/widgets/plotutils.py
orangecontrib/geo/widgets/tests/test_plotutils.py

Zooming is too fast and in most cases zooming in is immediatelly followed by zooming all the way out.
The latter happens because the condition was `if ev.delta() > 0: ... else: ...` instead of `if ev.delta() > 0: ... elif ev.delta() < 0: ...`. Apparently, the zoom-in event can be followed by a number of events with delta equal to 0, which was interpreted as zooming out. :)
Fixes #140. Cmd-0 is less necessary.
- Use `np.sign(ev.delta())` (which can also equal 0)
- Use floats for zoom level, a suitable step seems to be 0.5. When using it, cast it to int.

MapViewBox: Fix zooming with trackpad; add zoom in and out on mouse clicks

---

.github/workflows/test.yml
tox.ini

Fixes #141.
Orange is also tested on Python 3.9, and so should be this add-on.

Add Python 3.9 to test matrix

---

orangecontrib/geo/widgets/owmap.py
orangecontrib/geo/widgets/plotutils.py
orangecontrib/geo/widgets/tests/test_owmap.py

Fixes #87.
- Add `dark` flag to description of tile providers.
- When the map is dark, set the color for Text role to white.

Geo Map: Show white labels on dark maps

---

.github/workflows/test.yml
orangecontrib/geo/widgets/tests/test_owmap.py
tox.ini

`colorpalette` module is deprecated and we wanted to remove it from Orange: https://github.com/biolab/orange3/pull/6135
Use classes from `colorpalettes` module instead

[FIX] Replace deprecated colorpalette with colorpalettes

---

orangecontrib/geo/widgets/owgeocoding.py

Fixes #152.
`setResizeMode` was removed some time after Qt 5.12 and has to be replaced with `setSectionResizeMode`.

Geo Coding: Replace obsolete call to setResizeMode

---

orangecontrib/geo/tests/test_utils.py
orangecontrib/geo/utils.py
orangecontrib/geo/widgets/owgeotransform.py
orangecontrib/geo/widgets/tests/test_owgeotransform.py

Fixes #144.
I improved the logic for selecting the variables with coordinates.
- If there are matching names, that's it (`find_lat_lon`).
- Otherwise, if there are more than three, select the first one for both (diagonal indicates that this has to be set).
- If there are two and one has an appropriate name, the remaining one has to be the other variables.
- Otherwise, select these two and, assuming the order is likely to be lat/lon, this is likely correct.
It follows the discussion from #130, the new point is the penultimate.
@ajdapretnar, maybe we should move this logic to `find_lat_lon`?

Geo Transform Improvements

---

orangecontrib/geo/utils.py

When translating into other languages, one can't add new candidate names for latitude and longitude without removing the existing.
Define the candidates as a string that is then split into names. This allows for arbitrary number of names.

Utils: give lat and lon candidates as list from split string

---

orangecontrib/geo/widgets/owchoropleth.py
orangecontrib/geo/widgets/tests/test_owchoropleth.py

Fixes #163.
Widget now stores selection by region ids, not indices. When selection is restored, missing region ids are ignored.

[FIX] Choropleth: Store selection by region ids, not indices

---

doc/widgets.json
orangecontrib/geo/widgets/owchoropleth.py
orangecontrib/geo/widgets/owgeocoding.py
orangecontrib/geo/widgets/owgeotransform.py
orangecontrib/geo/widgets/owmap.py

Keywords were given in lists, so translations had to have the same number of keywords (or less - but not more).
Now they are written in string.

Keywords: changed from list to string

---

orangecontrib/geo/widgets/__init__.py

- Name is currently deduced from entry point name in setup.py. This is not translatable.
- Description (show as tooltip) is missing.
Add `NAME` (same as before, `"Geo"`) and `DESCRIPTION` to category globals.

Add category name and description

---

.github/workflows/test-translations.yml
i18n/si/msgs.jaml
i18n/si/trubar-config.yaml
i18n/trans.sh

Add Slovenian translations and corresponding tests

Add Slovenian translations

---

orangecontrib/geo/__init__.py
orangecontrib/geo/tests/test_utils.py
setup.py
tox.ini

As decided when we added a workaround for `Table.get_column`, the time arrived to require Orange 3.34 and remove the workaround (and defuse the time bomb).

Require Orange 3.34

---

orangecontrib/geo/widgets/owgeocoding.py
orangecontrib/geo/widgets/tests/test_owgeocoding.py

Fixes #179.
In `set_data`, we have
```
self.openContext(data)
self.region_attr_changed()
```
`region_attr_changed()` is the callback for combo with the attribute, and it includes a heuristic for setting the identifier type, thus overriding the value from the context.
Besides, it calls `commit`, which is ugly - `set_data` was not calling commit on it's own because it called `region_attr_changed`, which does it. Forget about proper implementation of auto_commit...
Reorganize the callbacks, and use heuristics for setting the type only if type is not recovered from the context (i.e., when no context matches).
Somebody should write tests for this. If nobody does it before the next release, we can still accept the PR as it is (if it's correct), because the widget is rather untested anyway.

GeoCoding: Don't override identifier type in set_data

---

orangecontrib/geo/mapper.py
setup.py

Previously, we needed to enabled cython-based speedups in Shapely. Starting with Shapely 2.0, equivalent speedups are available in every installation. Function `enable` has no effect and will be removed in future versions, they say.
- Remove the code that checks whether speedups are available and enables them.
- Require Shapely>=2

Mapper: Remove deprecated function

---

i18n/si/msgs.jaml
orangecontrib/geo/widgets/plotutils.py

Several tile providers went commercial or ceased to work.
Fixes #188, fixes #173.
Remove Mapnik and Stamen, add Greyscale from Geofabrik and Light from Carto.
Here's an interesting site to find alternative providers: https://mc.bbbike.org/mc/. Note, though, that most of them require an API_KEY and are thus not suitable for our use.

Remove unavailable tile providers, add some new
