biolab/orange3-geo

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
> Github: Issue and PR templates

- orangecontrib/geo/mapper.py
- orangecontrib/geo/widgets/owgeocoding.py
Fixes https://github.com/biolab/orange3-geo/issues/8
Auto-detect string type when selected string attribute changes.
> OWGeocoding: auto detect str attribute type when encoding

- orangecontrib/geo/widgets/owchoropleth.py
Fixes https://github.com/biolab/orange3-geo/issues/15
> OWChoropleth: in legend, only show discrete values contained in results

- orangecontrib/geo/cc_cities.py
- orangecontrib/geo/geojson/make-geojson.sh
- orangecontrib/geo/mapper.py
- orangecontrib/geo/widgets/owgeocoding.py
Fixes https://github.com/biolab/orange3-geo/issues/16, fixes https://github.com/biolab/orange3-geo/issues/13.
> GeoMapper: override matching

- orangecontrib/geo/widgets/owchoropleth.py
Send selection fails on no selection (or no data)
Some checks in `commit`.
Upgrade to new signals (Outputs and Inputs).
> [FIX] Choropleth Map: Send selection fails on no selection

- .gitignore
- orangecontrib/geo/widgets/owgeocoding.py
- orangecontrib/geo/widgets/owmap.py
- orangecontrib/geo/widgets/tests/test_owmap.py
These two widgets still use old signals.
New signals
Also add some lines to `.gitignore`.
> New signals: Geo Map & Geocoding

- orangecontrib/geo/widgets/owmap.py
- orangecontrib/geo/widgets/tests/test_owmap.py
> [FIX] Geo Map: linear gradient pass through black

- orangecontrib/geo/datasets/HDI-small.csv
- orangecontrib/geo/utils.py
- orangecontrib/geo/widgets/owgeocoding.py
- orangecontrib/geo/widgets/tests/test_owgeocoding.py
Fixes #36 and window geometry.
Changed default to Encode.
Set window size depending on selection (hide when no unmatched instances).
Small cosmetic fixes.
> Geocoding: Set window size

- orangecontrib/geo/widgets/owmap.py
Fixes #42.
Replaced Thunderforst with OpenTopoMap.
> Remove Thunderforest in favour of OpenTopoMap

- orangecontrib/geo/widgets/owmap.py
Fixes #60 
Increase timeout for drawing to 60 seconds.
> OWGeoMap: increase timeout for drawing

- orangecontrib/geo/mapper.py
Falling test on Travis.
Transform centroids given to KDTree to numpy ndarray.
> KDTree: transform centroids into numpy array

- orangecontrib/geo/widgets/owmap.py
GeoMap doesn't import with the split canvas.
Fixs imports to work with both options.
> Import GeoMap with new base widget

- doc/widget_data.json
Add widget_data.json for widget-catalog on Orange website.
> Add widget_data.json.

- orangecontrib/geo/widgets/owmap.py
- setup.py
Undo f4625d18c71bc4a1b401d2f326cbce87d21c33b0 becouse it brakes compatibility with old and new versions of orange.
> [FIX] OWMap: fix compatibility issue with core orange

- orangecontrib/geo/widgets/owmap.py
Resolve deprecated warnings for string settings and ProgressBar processEvents argument.
> OWMap: resolve deprecated warnings

- LICENSE.txt
- MANIFEST.in
The license is specified but a copy of it was not included in the release which is a requirement for conda-forge.
> Add license file

- .travis.yml
- orangecontrib/geo/widgets/owgeocoding.py
- setup.py
Fixes crash because of deprecated Table.concatenate for columns.
Replace it with Table.transform
> [FIX] OWGeocoding: data concatenation error

- orangecontrib/geo/widgets/owgeocoding.py
Resolve deprecated variables as strings in settings.
> [FIX] OWGeocoding deprecated settings

- MANIFEST.in
- README.pypi
- setup.py
README for Github and README for PyPi should not be the same. PyPi doesn't format markdown and the description is often too long.
Have two separate READMEs - one for Github and one for PyPi (which is also shown in the add-on dialogue).
> Provide a separate readme file for PyPi

- .travis.yml
Fixes falling travis
Update pip version and pin qt below 5.14
> [FIX] Falling Travis

- orangecontrib/geo/widgets/owmap.py
- orangecontrib/geo/widgets/plotutils.py
- orangecontrib/geo/widgets/tests/test_owmap.py
- orangecontrib/geo/widgets/tests/test_plotutils.py
In preparation for #89, move plotting utils for maps into a separate file and update OWMap accordingly.
I have decided to make it a separate PR to test that the change doesn't break OWMap.
> [ENH] Move map plot utils to separate file

- .coveragerc
- .travis.yml
- codecov.yml
> [ENH] Add Codecov

- .travis.yml
- CONTRIBUTING.md
- MANIFEST.in
- README.md
- orangecontrib/geo/geojson/make-geojson.sh
- setup.py
Some cleanup before the next releas.
> [ENH] Repository cleanup

- orangecontrib/geo/widgets/owchoropleth.py
Fixes #97 and some other issues I found during testing.
> [FIX] OWChoropleth crashes

- orangecontrib/geo/widgets/owmap.py
If all potential lat/long attributes are removed at once and then re-added the map doesn't update to new data because effective variables are empty which means they are the same.
If no valid lat/long attribute selection exists the set `self.data = None`. This mimics the behavior of Scatter plot with no continues variables.
> [FIX] OWMap: updating on removing/adding lat and long

- orangecontrib/geo/widgets/owchoropleth.py
- orangecontrib/geo/widgets/owmap.py
- orangecontrib/geo/widgets/tests/test_owchoropleth.py
Falling tests for empty Table on OWMap. The same issue applies to OWChoropleth.
> [FIX] Empty data crash

- .travis.yml
- setup.py
OWChoropleth needs the latest palettes from Orange.
> Raise minimum Orange version

- orangecontrib/geo/widgets/owchoropleth.py
- orangecontrib/geo/widgets/owmap.py
> [FIX] Change latitude and longitude order

- orangecontrib/geo/widgets/owmap.py
Fixes #53. 
Latitude and longitude checkboxes are now searchable.
Other checkboxes are searchable by inheritance (PlotGui).
> Geo Map: Searchable comboBox

- orangecontrib/geo/widgets/owchoropleth.py
Continuation of #53 for Choropleth.
Add searchable comboboxes for cb that are domain-dependent.
> Choropleth: add searchable combobox

- orangecontrib/geo/widgets/owchoropleth.py
- orangecontrib/geo/widgets/owmap.py
Fix falling tests from duplicate variable names.
> Fix duplicate variable names

- orangecontrib/geo/widgets/owchoropleth.py
- orangecontrib/geo/widgets/owmap.py
- orangecontrib/geo/widgets/tests/test_owchoropleth.py
Some test failed due to deprecations and added automated summaries
- Fix deprecated calls
- Remove manual summaries in Choropleth Map since now they are provided by Orange
> Fix failing tests

- doc/conf.py
Fixes missing links in documentation.
Same as https://github.com/biolab/orange3-educational/pull/119/files.
> Fix building documentation

- doc/conf.py
Fixes missing links in documentation.
> Documentation: fix markdown compiling

- orangecontrib/geo/widgets/owchoropleth.py
- orangecontrib/geo/widgets/owmap.py
Fixes #122. 
Make OWGeoMap and OWChoropleth a tad smaller (as they open pretty big, about 1/2-1/3 of the screen).
> Fix widget geometry

- orangecontrib/geo/widgets/owchoropleth.py
- orangecontrib/geo/widgets/owmap.py
Fixes #123. 
Name boxes and set spacing to 0.
> Organize layout in ControlArea

- orangecontrib/geo/widgets/owchoropleth.py
- orangecontrib/geo/widgets/owmap.py
Fixes #105. 
Format Geo Map and Choropleth tooltips.
> Geo Map and Choropleth: tooltips

- orangecontrib/geo/widgets/owgeocoding.py
- setup.py
Unlock table.
To do: Update requirement.
> Geo Coding: Unlock table

- orangecontrib/geo/widgets/owgeocoding.py
Ref: https://github.com/biolab/orange3-geo/issues/135
Show/hide main area on 'is_decoding' change.
> owgeocoding: Rework how/when mainArea is visible

- .github/workflows/test.yml
- orangecontrib/geo/mapper.py
- orangecontrib/geo/utils.py
- tox.ini
Fixes: https://github.com/biolab/orange3-geo/issues/156
* Use MultPolygon.geoms to iterate over.
* Load geometry only when needed and make it more robust avoid deadlocking in case of errors.
> [FIX] mapper: Fix deadlock in case of an error in geometry parsing

- MANIFEST.in
- i18n/si/trubar-config.yaml
- i18n/trans.sh
- i18n/trubar-config.yaml
- setup.py
- tox.ini
Prepare multilingual configuration.
> [ENH] Multilingual package
